/**
 ******************************************************************************
 * @file           : main_ex2_rx_terminal_lab04.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
 
#include "stm32f4xx.h"
#include "uart_lab04.h"
#include <stdint.h>

#define LED_PIN   (1U << 5) /* LD2 PA5 */

static void delay(volatile uint32_t n) { while(n--) {} }

static void gpio_led_init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    GPIOA->MODER &= ~(3U << (5U*2U));
    GPIOA->MODER |=  (1U << (5U*2U));
}

static void led_on(void)  { GPIOA->BSRR = LED_PIN; }
static void led_off(void) { GPIOA->BSRR = (LED_PIN << 16); }

static void led_blink_times(uint32_t n)
{
    for (uint32_t i = 0; i < n; i++) {
        led_on();  delay(600000);
        led_off(); delay(600000);
    }
}

static uint32_t str_len(const char* s)
{
    uint32_t n = 0;
    while (s && s[n]) n++;
    return n;
}

static int str_eq(const char* a, const char* b)
{
    uint32_t i = 0;
    while (a[i] && b[i]) {
        if (a[i] != b[i]) return 0;
        i++;
    }
    return (a[i] == '\0' && b[i] == '\0');
}

int main(void)
{
    gpio_led_init();

    const uint32_t baud = 115200;
    uart2_init(baud, 1);

    uart2_write_str("\r\nSistema listo.\r\n");
    uart2_write_str("Escriba una linea y presione ENTER.\r\n");
    uart2_write_str("Comandos: ON | OFF | LEN\r\n\r\n");

    char buf[64];
    uint32_t idx = 0;
    uint32_t last_len = 0;

    while (1)
    {
        char c = uart2_read_char_blocking();

        /* Eco opcional */
        uart2_write_char(c);

        if (c == '\r' || c == '\n') {
            uart2_write_str("\r\n");
            buf[idx] = '\0';

            if (str_eq(buf, "ON")) {
                led_on();
                uart2_write_str("OK: LED ON\r\n");
            } else if (str_eq(buf, "OFF")) {
                led_off();
                uart2_write_str("OK: LED OFF\r\n");
            } else if (str_eq(buf, "LEN")) {
                uart2_write_str("LEN=");
                uart2_write_u32(last_len);
                uart2_write_str("\r\n");
            } else {
                last_len = str_len(buf);
                uart2_write_str("BLINK ");
                uart2_write_u32(last_len);
                uart2_write_str(" times\r\n");
                led_blink_times(last_len);
            }

            idx = 0;
        } else {
            if (idx < (sizeof(buf) - 1U)) {
                buf[idx++] = c;
            } else {
                idx = 0;
                uart2_write_str("\r\nERROR: overflow\r\n");
            }
        }
    }
}
